[build]
builder = "NIXPACKS"
buildCommand = "composer install --no-dev --optimize-autoloader && npm ci && npm run build"

[deploy]
preDeployCommand = "php artisan migrate --force && php artisan db:seed --force"
